### ISSUE TITLE
crawl: command not found

### ISSUE THREAD

**Issue by JianyuZhao7** [crestonbunch/tbcnn#1]
Hi. I am stuck in this step: " crawl algorithms --out crawler/data/algorithms.pkl " with problem  "crawl: command not found" . Can you help me?

**Comment by crestonbunch** [comment]
Hi,

Make sure you have set up the virtual environment and you have activated it with ```$ source venv/bin/activate```

This will setup the crawl, vectorize, sample, and classify commands.

Edit: Make sure you did not forget to run ```$ python setup.py develop``` inside the virtual environment. The console commands above are defined in setup.py.

**Comment by JianyuZhao7** [comment]
Thanks. I've solved this problem. The reason is I forgot the step: $ python setup.py develop.
