### ISSUE TITLE
Got exceptions when running the crawl command, request for uploading the dataset.

### ISSUE THREAD

**Issue by wanyao1992** [crestonbunch/tbcnn#3]
Dear authors,

Thanks for sharing you code. While running the code under the instructions in README file, I still get an exception when running the crawl command.
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sevko/portfolio/master/algorithms/sorting/mergesort.py (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f19af05ab10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
Could you also upload the data directory to the repository if the data is not too large, so I don't need to crawl the data myself.

Thanks.

**Comment by crestonbunch** [comment]
Good idea! I put the algorithms.pkl file from my experiments into crawler/algorithms.zip.
