### ISSUE TITLE
Regarding the TBCNN Impl.

### ISSUE THREAD

**Issue by FalconLK** [crestonbunch/tbcnn#9]
Hello, 

Thank you for the great impl. 

I've been trying to understand your impl. By the way, does the impl also work without CUDA? if not, which part of code should I modify to make it work without CUDA? 

Thank you very much and have a great day!

**Comment by bdqnghi** [comment]
this implementation is based on tensorflow, you can enable Cuda training by setting something like : 

os.environ['CUDA_VISIBLE_DEVICES'] = "1"

to enable GPU training

**Comment by FalconLK** [comment]
Thank you very much 👍
